{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "adcb7744-c12f-43f4-86b2-7700ea013a69",
   "metadata": {},
   "outputs": [],
   "source": [
    "import os\n",
    "from flask import Flask, request, jsonify\n",
    "from flask_login import LoginManager, UserMixin, login_user, logout_user, login_required, current_user\n",
    "from flask_cors import CORS\n",
    "from werkzeug.security import generate_password_hash, check_password_hash\n",
    "import sqlite3\n",
    "from datetime import datetime\n",
    "\n",
    "app = Flask(__name__)\n",
    "app.secret_key = os.getenv('SECRET_KEY', 'your-secret-key')\n",
    "CORS(app, supports_credentials=True)\n",
    "login_manager = LoginManager()\n",
    "login_manager.init_app(app)\n",
    "login_manager.login_view = 'login'\n",
    "\n",
    "DB_PATH = os.path.join(os.path.dirname(__file__), 'app.db')\n",
    "\n",
    "def init_db():\n",
    "    with sqlite3.connect(DB_PATH) as conn:\n",
    "        c = conn.cursor()\n",
    "        c.execute('''CREATE TABLE IF NOT EXISTS users (\n",
    "            id INTEGER PRIMARY KEY AUTOINCREMENT,\n",
    "            email TEXT UNIQUE NOT NULL,\n",
    "            password_hash TEXT NOT NULL,\n",
    "            created_at TIMESTAMP\n",
    "        )''')\n",
    "        c.execute('''CREATE TABLE IF NOT EXISTS subscriptions (\n",
    "            id INTEGER PRIMARY KEY AUTOINCREMENT,\n",
    "            user_id INTEGER,\n",
    "            is_active BOOLEAN,\n",
    "            start_date TIMESTAMP,\n",
    "            FOREIGN KEY (user_id) REFERENCES users(id)\n",
    "        )''')\n",
    "        conn.commit()\n",
    "\n",
    "class User(UserMixin):\n",
    "    def __init__(self, id, email):\n",
    "        self.id = id\n",
    "        self.email = email\n",
    "\n",
    "@login_manager.user_loader\n",
    "def load_user(user_id):\n",
    "    with sqlite3.connect(DB_PATH) as conn:\n",
    "        c = conn.cursor()\n",
    "        c.execute('SELECT id, email FROM users WHERE id = ?', (user_id,))\n",
    "        user = c.fetchone()\n",
    "        if user:\n",
    "            return User(user[0], user[1])\n",
    "        return None\n",
    "\n",
    "if not os.path.exists(DB_PATH):\n",
    "    init_db()\n",
    "\n",
    "@app.route('/api/register', methods=['POST'])\n",
    "def register():\n",
    "    data = request.get_json()\n",
    "    email = data.get('email')\n",
    "    password = data.get('password')\n",
    "    if not email or not password:\n",
    "        return jsonify({'error': 'Email and password required'}), 400\n",
    "    with sqlite3.connect(DB_PATH) as conn:\n",
    "        c = conn.cursor()\n",
    "        try:\n",
    "            password_hash = generate_password_hash(password)\n",
    "            c.execute('INSERT INTO users (email, password_hash, created_at) VALUES (?, ?, ?)',\n",
    "                      (email, password_hash, datetime.utcnow()))\n",
    "            user_id = c.lastrowid\n",
    "            c.execute('INSERT INTO subscriptions (user_id, is_active, start_date) VALUES (?, ?, ?)',\n",
    "                      (user_id, False, datetime.utcnow()))\n",
    "            conn.commit()\n",
    "            user = User(user_id, email)\n",
    "            login_user(user)\n",
    "            return jsonify({'message': 'Registered successfully', 'user': {'email': email}}), 201\n",
    "        except sqlite3.IntegrityError:\n",
    "            return jsonify({'error': 'Email already exists'}), 400\n",
    "\n",
    "@app.route('/api/login', methods=['POST'])\n",
    "def login():\n",
    "    data = request.get_json()\n",
    "    email = data.get('email')\n",
    "    password = data.get('password')\n",
    "    with sqlite3.connect(DB_PATH) as conn:\n",
    "        c = conn.cursor()\n",
    "        c.execute('SELECT id, email, password_hash FROM users WHERE email = ?', (email,))\n",
    "        user = c.fetchone()\n",
    "        if user and check_password_hash(user[2], password):\n",
    "            user_obj = User(user[0], user[1])\n",
    "            login_user(user_obj)\n",
    "            return jsonify({'message': 'Logged in successfully', 'user': {'email': user[1]}}), 200\n",
    "        return jsonify({'error': 'Invalid credentials'}), 401\n",
    "\n",
    "@app.route('/api/logout', methods=['POST'])\n",
    "@login_required\n",
    "def logout():\n",
    "    logout_user()\n",
    "    return jsonify({'message': 'Logged out successfully'}), 200\n",
    "\n",
    "@app.route('/api/check_access', methods=['GET'])\n",
    "def check_access():\n",
    "    if not current_user.is_authenticated:\n",
    "        return jsonify({'authenticated': False, 'subscribed': False}), 401\n",
    "    with sqlite3.connect(DB_PATH) as conn:\n",
    "        c = conn.cursor()\n",
    "        c.execute('SELECT is_active FROM subscriptions WHERE user_id = ?', (current_user.id,))\n",
    "        sub = c.fetchone()\n",
    "        subscribed = sub and sub[0]\n",
    "        return jsonify({'authenticated': True, 'subscribed': subscribed}), 200\n",
    "\n",
    "@app.route('/api/subscription/activate', methods=['POST'])\n",
    "@login_required\n",
    "def activate_subscription():\n",
    "    with sqlite3.connect(DB_PATH) as conn:\n",
    "        c = conn.cursor()\n",
    "        c.execute('UPDATE subscriptions SET is_active = ?, start_date = ? WHERE user_id = ?',\n",
    "                  (True, datetime.utcnow(), current_user.id))\n",
    "        conn.commit()\n",
    "        return jsonify({'message': 'Subscription activated'}), 200\n",
    "\n",
    "if __name__ == '__main__':\n",
    "    app.run(debug=True)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.13"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
